exports.carMakes = [
    { Make_Name: 'ASTON MARTIN' },
    { Make_Name: 'TESLA' },
    { Make_Name: 'JAGUAR' },
    { Make_Name: 'MASERATI' },
    { Make_Name: 'LAND ROVER' },
    { Make_Name: 'ROLLS ROYCE' },
    { Make_Name: 'TOYOTA' },
    { Make_Name: 'MERCEDES-BENZ' },
    { Make_Name: 'BMW' },
    { Make_Name: 'BUGATTI' },
    { Make_Name: 'MINI' },
    { Make_Name: 'FORD' },
    { Make_Name: 'LINCOLN' },
    { Make_Name: 'MERCURY' },
    { Make_Name: 'LOTUS' },
    { Make_Name: 'CHEVROLET' },
    { Make_Name: 'BUICK' },
    { Make_Name: 'CADILLAC' },
    { Make_Name: 'GMC' },
    { Make_Name: 'MAZDA' },
    { Make_Name: 'HONDA' },
    { Make_Name: 'ACURA' },
    { Make_Name: 'DODGE' },
    { Make_Name: 'CHRYSLER' },
    { Make_Name: 'NISSAN' },
    { Make_Name: 'INFINITI' },
    { Make_Name: 'MITSUBISHI' },
    { Make_Name: 'VOLKSWAGEN' },
    { Make_Name: 'JEEP' },
    { Make_Name: 'VOLVO' },
    { Make_Name: 'FIAT' },
    { Make_Name: 'ALFA ROMEO' },
    { Make_Name: 'RAM' },
    { Make_Name: 'HYUNDAI' },
    { Make_Name: 'KIA' },
    { Make_Name: 'LAMBORGHINI' },
    { Make_Name: 'SUZUKI' },
    { Make_Name: 'LEXUS' },
    { Make_Name: 'SUBARU' },
    { Make_Name: 'PONTIAC' },
    { Make_Name: 'ISUZU' },
    { Make_Name: 'SAAB' },
    { Make_Name: 'SPRINTER (DODGE OR FREIGHTLINER)' },
    { Make_Name: 'AUDI' },
    { Make_Name: 'BENTLEY' },
    { Make_Name: 'PORSCHE' },
    { Make_Name: 'CAN-AM' },
    { Make_Name: 'FERRARI' },
    { Make_Name: 'HUMMER' },
    { Make_Name: 'DAEWOO' }
]
